- 판다스는 표 형식의 데이터나 다양한 형태의 데이터를 다루는 데 초점을 맞춰 설계

In [2]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

C:\Users\lockd\anaconda3\envs\pyTest\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\lockd\anaconda3\envs\pyTest\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
C:\Users\lockd\anaconda3\envs\pyTest\lib\site-packages\numpy\.libs\libopenblas64__v0.3.23-246-g3d31191b-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


### 5.1 판다스 자료구조 소개
#### 1) Series : 일련의 객체를 담을 수 있는 1차원 배열같은 자료구조

In [2]:
#Series
obj = pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
#배열과 색인 객체는 array와 index속성을 통해 얻을 수 있음
print(obj.array)
print(obj.index)

<PandasArray>
[4, 7, -5, 3]
Length: 4, dtype: int64
RangeIndex(start=0, stop=4, step=1)


In [3]:
obj2 = pd.Series([4,7,-5,3], index=["d","b","a","c"])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

- d b a c는 정수가 아닌 문자열이 포함되어있지만 색인의 배열로 해석
- 배열을 사용해서 값을 걸러내거나 스칼라 곱셈을 수행하거나 수학함수를 적용하는 등 넘파이 배열 연산을 수행해도 색인과 값 연결은 유지

In [4]:
obj2[obj2>0]

d    4
b    7
c    3
dtype: int64

In [5]:
obj2["a"]

-5

In [6]:
import numpy as np

In [7]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [10]:
#딕셔너리 객체로부터 Series 객체를 생성할 수도 있음
sdata = {"Ohio":35000, "Texas":71000, "Oregon":16000, "Utah":5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [11]:
#다시 딕셔너리로 변환할수도있음
obj3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [13]:
#색인을 직접 지정할 수도 있음
states = ["California","Ohio","Oregon","Texas"]
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [14]:
#누락된 데이터 찾기
pd.isna(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [15]:
pd.notna(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [16]:
#인스턴스 메서드도 존재
obj4.isna()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [17]:
#산술연산에서 색인과 레이블로 자동 정렬하는 기능
obj3+obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [20]:
#Series 객체와 색인은 모두 name속성을 가지며 이 속성은 판다스의 다른 기능들과 통합되어 있음
obj4.name = "population"
obj4.index.name = "state"
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

#### 2) DataFrame :표같은 스프레드시트 형식의 자료구조. 
- 행과 열에 대한 인덱스를 가지며 색인의 모양이 같은 Series 객체를 담고 있는 파이썬 딕셔너리로 생각하면 편함

In [21]:
#DataFrame 생성
data = {"state":["Ohio", "Ohio","Ohio", "Nevada", "Nevada", "Nevada"],
       "year": [2000,2001,2002,2001,2002,2003],
       "pop": [1.5,1.7,3.6,2.4,2.9,3.2]}
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [22]:
#columns을 원하는 순서대로 지정하면 해당 순서로 정렬
pd.DataFrame(data, columns=["year","state","pop"])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [23]:
#없는값을 columns에 넘기면 결측치가 표시됨
frame2 = pd.DataFrame(data,columns=["year", "state","pop","debt"])
frame2

year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [24]:
#딕셔너리, 점 표기법 모두 접근 가능
frame2["state"]

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [25]:
frame2.state

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [26]:
#반환된 Series 객체가 DataFrame과 같은 색인을 가지면 알맞은 값으로 name 속성이 채워짐
frame2.loc[1] #인덱스기준

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [27]:
frame2.iloc[2] #행기준

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: 2, dtype: object

In [33]:
#대입으로 열 수정 가능
frame2["debt"] = 16.5
frame2

year   state  pop  debt
0  2000    Ohio  1.5  16.5
1  2001    Ohio  1.7  16.5
2  2002    Ohio  3.6  16.5
3  2001  Nevada  2.4  16.5
4  2002  Nevada  2.9  16.5
5  2003  Nevada  3.2  16.5

In [35]:
frame2["debt"] = np.arange(6.)
frame2

year   state  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.0
3  2001  Nevada  2.4   3.0
4  2002  Nevada  2.9   4.0
5  2003  Nevada  3.2   5.0

In [36]:
#대입하려는값의 길이가 DataFrame의 길이와 동일하지 않으면 결측치 대입
val = pd.Series([-1.2, -1.5, -1.7], index = ["two", "four", "five"])
frame2["debt"] = val
frame2

year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6   NaN
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9   NaN
5  2003  Nevada  3.2   NaN

In [37]:
#del 예약어를 사용해 삭제 가능
frame2["eastern"] = frame2["state"] == "Ohio" #점 표기법은 안됨
frame2

year   state  pop  debt  eastern
0  2000    Ohio  1.5   NaN     True
1  2001    Ohio  1.7   NaN     True
2  2002    Ohio  3.6   NaN     True
3  2001  Nevada  2.4   NaN    False
4  2002  Nevada  2.9   NaN    False
5  2003  Nevada  3.2   NaN    False

In [38]:
# 새 열을 삭제
del frame2["eastern"]

In [39]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [41]:
#중첩된 딕셔너리를 이용해서 데이터를 생성
populations = {"Ohio":{2000:1.5, 2001:1.7, 2002:3.6}, "Nevada":{2001:2.4, 2002:2.9}}
frame3 = pd.DataFrame(populations)
frame3

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [42]:
frame3.T

2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [43]:
pd.DataFrame(populations, index=[2001,2002,2003])

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     NaN

In [44]:
pdata = {"Ohio":frame3["Ohio"][:-1],
        "Nevada":frame3["Nevada"][:2]} #색인을 직접 지정 할 수도 있다
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [45]:
# DataFrame의 색인과 열에 name속성이 설정되어 있다면 이 정보도 함께 출력됨
frame3.index.name = "year"
frame3.columns.name = "state"
frame3

state  Ohio  Nevada
year               
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [46]:
#DataFrame에 포함된 2차원 형태의 ndarray로 반환 => to_numpy 메서드
frame3.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

In [47]:
#서로 다른 자료형을 갖는다면 모든 열을 수용하기 위해 반환된 배열의 자료형이 선택
frame2.to_numpy()

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, nan],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

### 3) 색인객체

In [49]:
#객체를 생성할 때 사용하는 배열이나 다른 순차적인 레이블은 내부적으로 색인으로 변환됨
obj = pd.Series(np.arange(3), index=["a","b","c"])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [50]:
index[1:]

Index(['b', 'c'], dtype='object')

- 색인 객체는 변경이 불가능
- append, difference. intersection, union, isin. delete ...

## 2.핵심기능
### 1) 재색인
- 새로운 색인에 적합하도록 객체를 새로 생성하는 기능

In [51]:
obj = pd.Series([4.5, 7.2, -5.3,3.6], index=["d","b","a",'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [52]:
obj2 = obj.reindex(["a","b","c","d","e"])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [53]:
obj3 = pd.Series(["blue","purple", "yellow"], index=[0,2,4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [54]:
obj3.reindex(np.arange(6), method="ffill")

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [55]:
#DataFrame에 대해서는 행 열 또는 둘 다 변경 가능
frame = pd.DataFrame(np.arange(9).reshape((3,3)), index=["a","c","d"], columns=["Ohio","Texas","California"])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [56]:
frame2 = frame.reindex(index = ["a","b","c","d"])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [57]:
states = ["Texas", "Utah", "California"]
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [58]:
frame.reindex(states, axis="columns")

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

- reindex의 인수
 - labels, index. columns, axis, method, 
 - fill_value : 비어있는 데이터를 채우기 위한 값

In [60]:
frame.loc[["a","d","c"], ["California", "Texas"]]

California  Texas
a           2      1
d           8      7
c           5      4

### 2) 하나의 행이나 열 사용하기 - drop 메서드

In [63]:
obj = pd.Series(np.arange(5.), index = ["a","b","c","d","e"])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [66]:
new_obj = obj.drop("c")
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [67]:
#데이터프레임에서는 행 열 모두 색인값 삭제 가능
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                   index = ["Ohio","Colorado","Utah", "New York"],
                   columns = ["one","two","three","four"])

In [69]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [70]:
#삭제하고 싶은 행 이름 넘기기
data.drop(index=["Colorado","Ohio"])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [71]:
data.drop(columns="two")

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [72]:
#열 값 삭제시 axis=1 또는 axis="columns" 인수로 넘기기
data.drop("two",axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

### 3) 색인하기, 선택하기,거르기

In [73]:
obj = pd.Series(np.arange(4.), index=["a","b","c","d"])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [74]:
obj["b"]

1.0

In [75]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [76]:
#loc 이용이 더 선호
obj.loc[["b","a","d"]]

b    1.0
a    0.0
d    3.0
dtype: float64

In [83]:
# []기반 색인은 정수가 포함될 경우 이를 레이블로 인식하고 색인의 자료형에 따라 작동 방식이 달라짐
obj1 = pd.Series([1,2,3],index=[2,0,1])
obj2 = pd.Series([1,2,3], index=["a","b","c"])
obj1[[0,1,2]]

0    2
1    3
2    1
dtype: int64

In [84]:
obj2[[0,1,2]]

a    1
b    2
c    3
dtype: int64

In [85]:
#loc를 이용하면 인덱스에 정수가 없으면 obj1.loc[[0,1,2]] 는 실패
# iloc 연산자 : 정수를 포함하고 있는지 여부와 관계없이 일관되게 작동하도록 정수로만 색인을 취함
obj1.iloc[[0,1,2]]

2    1
0    2
1    3
dtype: int64

In [86]:
obj2.iloc[[0,1,2]]

a    1
b    2
c    3
dtype: int64

In [87]:
data = pd.DataFrame(np.arange(16).reshape((4,4)), index=["Ohio","Colorado","Utah", "New York"],columns = ["one","two","three","four"])

In [88]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [89]:
data["two"]

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [90]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [92]:
#행선택
data[data["three"]>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [111]:
#불리언
data < 5

one  two  three  four
Ohio    0    0      0     0

In [95]:
#값 할당
data[data<5]=0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [102]:
data.loc["Colorado"]

one      0
two      5
three    6
four     7
Name: Colorado, dtype: int32

In [104]:
#여러행을 선택해서 새 DF 생성
data.loc[["Colorado", "New York"]]

one  two  three  four
Colorado    0    5      6     7
New York   12   13     14    15

In [106]:
data.iloc[[2,1]]

one  two  three  four
Utah        8    9     10    11
Colorado    0    5      6     7

In [107]:
data.iloc[2,[3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [108]:
data.iloc[[1,2],[3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [109]:
data.loc[:"Utah", "two"]

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [112]:
data.iloc[:,:3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [113]:
data.loc[data.three>2]

one  two  three  four
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [118]:
ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [121]:
#색인의 함정 - 정수색인 or 레이블 색인
ser[-1]

KeyError: -1

In [116]:
#정수기반의 색인 사용
ser2 = pd.Series(np.arange(3.), index=["a","b","c"])
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [117]:
ser2[-1]

2.0

In [122]:
#연쇄색인
data.loc[:,"one"] = 1
data

one  two  three  four
Ohio        1    0      0     0
Colorado    1    5      6     7
Utah        1    9     10    11
New York    1   13     14    15

In [123]:
data.iloc[2] = 5 #정수색인엔 iloc, 레이블에 대해서는 loc
data

one  two  three  four
Ohio        1    0      0     0
Colorado    1    5      6     7
Utah        5    5      5     5
New York    1   13     14    15

In [124]:
#값 대입 가능
data.loc[:,"one"] = 1
data

one  two  three  four
Ohio        1    0      0     0
Colorado    1    5      6     7
Utah        1    5      5     5
New York    1   13     14    15

In [127]:
data.iloc[2] = 5
data

one  two  three  four
Ohio        1    0      0     0
Colorado    1    5      6     7
Utah        5    5      5     5
New York    1   13     14    15

In [129]:
#단일 loc 연산 사용
#data.loc[data.three == 5]["Three"]=6  #error
data.loc[data.three == 5, "three"] =6
data

one  two  three  four
Ohio        1    0      0     0
Colorado    1    5      6     7
Utah        5    5      6     5
New York    1   13     14    15

In [132]:
### 4) 산술 연산과 데이터 정렬
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=["a","c","d","e"])
s2 = pd.Series([-2.1,3.6,-1.5,4,3.1], index=["a","c","e","f","g"])

In [133]:
#겹치지 않은 부분은 결측치
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [136]:
df1 = pd.DataFrame(np.arange(9.).reshape((3,3)), columns=list("bcd"), index=["Ohio", "Texas", "Colorado"])
df2= pd.DataFrame(np.arange(12.).reshape((4,3)), columns=list("bde"), index=["Utah","Ohio","Texas", "Oregon"])
df1+df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [140]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)), columns=list("abcd"))
df2= pd.DataFrame(np.arange(20.).reshape((4,5)), columns=list("abcde"))

In [141]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [142]:
df2.loc[1,"b"] = np.nan

In [143]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [144]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [146]:
#### DataFrame과 Series 간의 연산
arr = np.arange(12.).reshape((3,4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [147]:
arr[0]

array([0., 1., 2., 3.])

In [148]:
arr - arr[0]
#연산은 각 행에 대해 한번씩만 수행 => 브로드캐스팅

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [157]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)), columns=list("bde"), index=["Utah","Ohio","Texas","Oregon"])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [158]:
series = frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [159]:
frame - series #브로드캐스팅

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [160]:
#각 행에 대해 연산을 수행하고 싶다면 산술 연산 메서드를 사용해 색인이 일치하도록 지정
series3= frame["d"]
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [161]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [156]:
frame.sub(series3, axis="index")

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

### 5) 함수적용과 매핑

In [164]:
#배열의 각 원소에 적용되는 유니버설 함수 적용 가능
frame = pd.DataFrame(np.random.standard_normal((4,3)), columns=list("bde"), index=["Utah","Ohio","Texas","Oregon"])
frame

b         d         e
Utah   -1.793997  0.090651 -0.022701
Ohio    1.583675  0.457003 -0.051796
Texas  -1.066536 -2.741650  2.491058
Oregon -1.405856  1.141408  1.160432

In [165]:
np.abs(frame)

b         d         e
Utah    1.793997  0.090651  0.022701
Ohio    1.583675  0.457003  0.051796
Texas   1.066536  2.741650  2.491058
Oregon  1.405856  1.141408  1.160432

In [166]:
def f1(x):
    return x.max() - x.min()

In [167]:
frame.apply(f1)

b    3.377672
d    3.883058
e    2.542854
dtype: float64

In [168]:
#열을 따라 적용
frame.apply(f1, axis="columns")

Utah      1.884647
Ohio      1.635472
Texas     5.232708
Oregon    2.566289
dtype: float64

In [169]:
def f2(x):
    return pd.Series([x.min(),x.max()], index=["min","max"])
frame.apply(f2)

b         d         e
min -1.793997 -2.741650 -0.051796
max  1.583675  1.141408  2.491058

In [170]:
### 6) 정렬과 순위
obj = pd.Series(np.arange(4), index=["d","a","b","c"])
obj

d    0
a    1
b    2
c    3
dtype: int32

In [171]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int32

In [172]:
frame = pd.DataFrame(np.arange(8).reshape((2,4)), index=["three","one"], columns=["d","a","b","c"])

In [173]:
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [174]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [175]:
frame.sort_index(axis="columns")

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [176]:
frame.sort_index(axis="columns", ascending=False) #내립차순

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [177]:
#값에 따라 정렬
obj = pd.Series([4,7,-3,2])
obj.sort_values() #결측치는 가장 마지막에 위치

2   -3
3    2
0    4
1    7
dtype: int64

In [178]:
#랭크
obj = pd.Series([7,-5,7,4,2,0,4])
obj.rank()
#동점이면 평균순위를 매겨 책정

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

### 7) 중복색인

In [179]:
obj = pd.Series(np.arange(5), index=["a","a","b","b","c"])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int32

In [180]:
obj.index.is_unique

False

In [181]:
obj["a"]

a    0
a    1
dtype: int32

In [182]:
df = pd.DataFrame(np.random.standard_normal((5,3)), index=["a","a","b","b","c"])
df

0         1         2
a -2.467441 -1.373975  0.964049
a  0.733535  1.150914  0.558665
b -0.465352  0.162541  0.899095
b  1.062930  0.420460 -1.522153
c  1.204686  1.162521 -0.573200

In [183]:
df.loc["b"]

0         1         2
b -0.465352  0.162541  0.899095
b  1.062930  0.420460 -1.522153

### 3. 기술통꼐 계산과 요약
- 합이나 평균같은 단일 값
- 축소 혹은 요약통계 범주

In [184]:
df = pd.DataFrame([[1.4,np.nan],[7.1,-4.5], [np.nan,np.nan],[0.75,-1.3]],index=["a","b","c","d"], columns=["one","two"])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [185]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [187]:
df.sum(axis="columns")

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [188]:
#NA가 포함되면 연산결과도 NA 이나 skipna를 통해 해결가능
df.sum(axis="index", skipna=False)

one   NaN
two   NaN
dtype: float64

In [189]:
#간접통계
df.idxmin()

one    d
two    b
dtype: object

In [190]:
df.idxmax()

one    b
two    d
dtype: object

In [191]:
#요약
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

#### 1) 상관관계와 공분산

In [192]:
price = pd.read_pickle("yahoo_price.pkl")
volume = pd.read_pickle("yahoo_volume.pkl")

In [194]:
returns = price.pct_change()
returns.tail()

AAPL      GOOG       IBM      MSFT
Date                                              
2016-10-17 -0.000680  0.001837  0.002072 -0.003483
2016-10-18 -0.000681  0.019616 -0.026168  0.007690
2016-10-19 -0.002979  0.007846  0.003583 -0.002255
2016-10-20 -0.000512 -0.005652  0.001719 -0.004867
2016-10-21 -0.003930  0.003011 -0.012474  0.042096

In [195]:
#두 Series의 상관관계를 계산
returns["MSFT"].corr(returns["IBM"])

0.49976361144151155

In [196]:
#공분산을 계산
returns["MSFT"].cov(returns["IBM"])

8.870655479703546e-05

In [197]:
returns["MSFT"].corr(returns["IBM"])

0.49976361144151155

In [198]:
#각 행렬상의 상관관계와 공분산 계산
returns.corr()

AAPL      GOOG       IBM      MSFT
AAPL  1.000000  0.407919  0.386817  0.389695
GOOG  0.407919  1.000000  0.405099  0.465919
IBM   0.386817  0.405099  1.000000  0.499764
MSFT  0.389695  0.465919  0.499764  1.000000

In [199]:
returns.cov()

AAPL      GOOG       IBM      MSFT
AAPL  0.000277  0.000107  0.000078  0.000095
GOOG  0.000107  0.000251  0.000078  0.000108
IBM   0.000078  0.000078  0.000146  0.000089
MSFT  0.000095  0.000108  0.000089  0.000215

In [201]:
returns.corrwith(returns["IBM"])

AAPL    0.386817
GOOG    0.405099
IBM     1.000000
MSFT    0.499764
dtype: float64

In [ ]:
### 2) 유일값, 값 세기, 멤버십

In [203]:
obj = pd.Series(["c","a","d","a","a","b","b","c","c"])
uniques = obj.unique()

In [204]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [205]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [206]:
pd.value_counts(obj.to_numpy(),sort=False)

c    3
a    3
d    1
b    2
dtype: int64

In [207]:
#불리언값
mask = obj.isin(["b","c"])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [208]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [210]:
#색인배열
to_match = pd.Series(["c","a","b","b","c","a"])
unique_vals = pd.Series(["c","b","a"])
indices = pd.Index(unique_vals).get_indexer(to_match)

In [211]:
indices

array([0, 2, 1, 1, 0, 2], dtype=int64)